# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 85528366a0b082e62824ff008ec12372bf551a79add901abba69048685deeb1767a3c0fbcb35493bfb740f9833ec63f86b77e364bc0ae3cff3caf7c2af6654c4

test:
  secret_key_base: 2091f381486178447d224e7dae53ea52e0951c8d917d1a326f9f43d320597b0964ca3e12db61f83dd418670cf2ce7f0078de8f828402c7ae0d60ddaddad3dcab

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
